server:
  port: 8010
spring:
  application:
    name: demo-consumer-movie-ribbon
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true