server:
  port: 8761 # 指定该Eureka实例的端口
eureka:
  instance:
      hostname: 192.168.230.129 # 指定该Eureka实例的主机名
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://192.168.230.129:8761/eureka/
spring:
  application:
    name: eureka