server:
  port: 8040
spring:
  application:
    name: demo-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/importtao/springcloud-parent/
          skipSslValidation: true
          search-paths: config
          username: importtao
          password: Sldzt723